### ISSUE TITLE
Cannot run the example

### ISSUE THREAD

**Issue by Gabriel-Gardin** [tomvictor/iotcore#17]
Hello, I'm trying to replicate the example but when I've tried to run the example I get:

_from djangoiot.shortcuts import device,subscribe
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'djangoiot.shortcuts'_

I also noted that the source code on github seems to be incomplete, am I missing something or the project is not ready to use yet?

I would be glad to help on this project.

**Comment by tomvictor** [comment]
Hi @Gabriel-Gardin Feel free to test out the newly added features and examples!
