### ISSUE TITLE
Correct Implementation

### ISSUE THREAD

**Issue by pigbite** [tomvictor/iotcore#5]
Hi 
I am fairly new to Python and looking for the best way of integrating MQTT with Django.  I've come across your library and it looks perfect.  I am just wondering however on the best way to implement the code so that the connection to the broker is made on Django startup and not on each view.  I also want to be able to trigger an event in the UI when a subscribed point changes.  

My application is visualising a building control application running on KNX. I have topics on a broker which would allow the UI to (a) trigger actions in the building (e.g. close a blind) and (b) see the state of devices in the building (e.g. the position of a blind).  Should something be changed in the building then I want the UI view to change when the subscribed topic changes.

How is this best handled with your library?  How might this be better than using (for example) Paho MQTT Javascript?  Is it possible to map the MQTT topics to a model inside Django?

Sorry if any of the questions are basic but that's my limited experience of Django/Python...

**Comment by aapris** [comment]
This looks like some kind of experiment, there is not even `shortcuts` or `broker` in djangoiot module (see example in readme). Don't waste your time here.

Django doesn't support MQTT or e.g. WebSockets very well, but e.g. [Flask does](https://pypi.org/project/Flask-MQTT/).

**Comment by Tomvictor** [comment]
Let me know the suggestion. We will work on this. I just started this as a experiment project. 
@aapris @pigbite 

Thanks for the feedback

**Comment by tomvictor** [comment]
Hi @aapris please check the new implementation and give your feedbacks.
Thanks

**Comment by tomvictor** [comment]
Fixed with Iotcore rust implementation
